//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotels
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public byte @class { get; set; }
        public string description { get; set; }
        public int available_rooms { get; set; }
    }
}
