//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tours
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int hotel_id { get; set; }
        public string departure_city { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime expiration_date { get; set; }
        public short price { get; set; }
        public string description { get; set; }
    }
}
