//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        
        public long Id { get; set; }

        [DisplayName("First name")]
        [Required(ErrorMessage = "This field is required")]
        public string first_name { get; set; }

        [DisplayName("Second Name")]
        [Required(ErrorMessage = "This field is required")]
        public string second_name { get; set; }

        [DisplayName("E-mail")]
        [Required(ErrorMessage = "This field is required")]
        public string email { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required")]
        public string password { get; set; }

        [DisplayName("Confirm password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required")]
        [Compare("password")]
        public string confirm_password { get; set; }

        public byte role_id { get; set; }
    }
}
